@TodoApi.Server_HostAddress = https://localhost:7174


GET {{TodoApi.Server_HostAddress}}/api/todoitems

###

POST {{TodoApi.Server_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "www",
  "isComplete": true
}

###
